---
  kubeansi:
    name: kubeansi
    domain: example.local
    lan_pxe:
      interface: ens37
      ip: 192.168.5.1
      netmask: 255.255.255.0
      gateway: false
      dhcp_start: 192.168.5.100
      dhcp_end: 192.168.5.200
    lan_control:
      interface: ens33
      ip: 192.168.25.129
      netmask: 255.255.255.0
      gateway: 192.168.25.2
    nameservers:
      - 8.8.4.4
      - 8.8.8.8

    lans:
      control:
        lan: 192.168.79.0
        prefix: 24
      # external:
      #   lan: 192.168.1.0
      #   prefix: 24
      #   gateway: 192.168.1.1

###################### DEFAULT VARIABLES ######################
  v_root:
    dir: /root

  v_tftpboot:
    dir: /var/lib/tftpboot

  v_bootstrap:
    dir: /var/lib/nfs/bootstrap

  v_centos7:
    repo_base: "http://mirror.centos.org/centos/7/os/x86_64"
    nameservers:
      - 8.8.4.4
      - 8.8.8.8
    root_password: "aQZP5m7xBRBt8rtk"
    repo_packages:
      - kernel
      - kernel-devel
      - grub2
      - grub2-efi-x64
      - shim-x64
      - efibootmgr
    packages:
      - authconfig
      - bc
      - bridge-utils
      - chrony
      - deltarpm
      - epel-release
      - gcc
      - git
      - htop
      - iftop
      - jq
      - mlocate
      - net-tools
      - ntp
      - python-devel
      - python2-pip
      - python2-simplejson
      - sg3_utils
      - sudo
      - tcpdump
      - vim-enhanced
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - kubelet
      - kubeadm
      - kubectl
#
      - -NetworkManager*
      - -cloud-init
      - -firewalld
      - -iwl*firmware
      - -postfix
      - -python-requests
      - -chrony

    repo_pip:
      - docker
...