---
  - name: Cargar fichero network
    include_vars:
      file: "{{v_root.dir}}/provision/network.yml"
      name: v_network
    delegate_to: localhost

  - name: Asignar IP a interfaces con _use y sin address
    set_fact:
      v_network_node: "{{ v_network_node | combine( { item: {'_ipv4': kubeansi.lans[v_network_node[item]._use].lan|ipmath(ansible_host.split('.')[3]|int) } },recursive=true ) }}"
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use in kubeansi.lans
      - v_network_node[item]._ipv4 is none
      - kubeansi.lans[v_network_node[item]._use].lan

  - name: debug
    debug:
      var: v_network_node[item]._ipv4

  - name: Ensure kubelet file config exist
    file:
      path: /etc/default/kubelet
      state: touch
      mode: '0644'

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{v_network_node[item]._ipv4}}
    with_items: "{{v_network_node}}"

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      enabled: yes
      state: restarted

  - name: Restart nodes
    reboot:
...