---
  - name: Cargar fichero network
    include_vars:
      file: "{{v_root.dir}}/provision/network.yml"
      name: v_network
    delegate_to: localhost

  - name: Cargar variable v_network_node
    set_fact:
      v_network_node: "{{ v_network[inventory_hostname]|default({}) }}"

  - name: Asignar IP a interfaces con _use y sin address
    set_fact:
      v_network_node: "{{ v_network_node | combine( { item: {'_ipv4': kubeansi.lans[v_network_node[item]._use].lan|ipmath(ansible_host.split('.')[3]|int) } },recursive=true ) }}"
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use in kubeansi.lans
      - v_network_node[item]._ipv4 is none
      - kubeansi.lans[v_network_node[item]._use].lan

  - name: Configure /etc/default/kubelet
    template:
      src: kubelet.j2
      dest: /etc/default/kubelet
      force: yes
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use == 'control'

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      enabled: yes
      state: restarted

  - name: Restart nodes
    reboot:
...