---
  - name: Cargar fichero network
    include_vars:
      file: "{{v_root.dir}}/provision/network.yml"
      name: v_network
    delegate_to: localhost

  - name: Cargar variable v_network_node
    set_fact:
      v_network_node: "{{ v_network[inventory_hostname]|default({}) }}"

  - name: Asignar IP a interfaces con _use y sin address
    set_fact:
      v_network_node: "{{ v_network_node | combine( { item: {'_ipv4': kubeansi.lans[v_network_node[item]._use].lan|ipmath(ansible_host.split('.')[3]|int) } },recursive=true ) }}"
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use in kubeansi.lans
      - v_network_node[item]._ipv4 is none
      - kubeansi.lans[v_network_node[item]._use].lan

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{v_network_node[item]._ipv4}}" --apiserver-cert-extra-sans="{{v_network_node[item]._ipv4}}"  --node-name master01 --pod-network-cidr=192.168.0.0/16
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use == 'control'

  - name: Create directories
    file:
      path: "{{ v_root.dir }}/.kube"
      state: directory

  - name: Copy file with owner and permissions
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ v_root.dir }}/.kube/config"
      remote_src: yes

  - name: Change file ownership, group and permissions
    file:
      path: "{{ v_root.dir }}/.kube/config"
      owner: root
      group: root

  - name: Install calico pod network
    command: kubectl create -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml
...