---
  - name: Cargar fichero network
    include_vars:
      file: "{{v_root.dir}}/provision/network.yml"
      name: v_network
    delegate_to: localhost

  - name: Cargar variable v_network_node
    set_fact:
      v_network_node: "{{ v_network[inventory_hostname]|default({}) }}"
      v_interfaces: []

  - name: Asignar IP a interfaces con _use y sin address
    set_fact:
      v_network_node: "{{ v_network_node | combine( { item: {'_ipv4': kubeansi.lans[v_network_node[item]._use].lan|ipmath(ansible_host.split('.')[3]|int) } },recursive=true ) }}"
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use in kubeansi.lans
      - v_network_node[item]._ipv4 is none
      - kubeansi.lans[v_network_node[item]._use].lan

  - name: Configurar los interfaces de red
    template:
      src: templates/ifcfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{item}}
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use is defined
      - v_network_node[item]._use is not none
      - v_network_node[item]._use != 'pxe'
    register: r_cambiados

  - name: Bajar los interfaces modificados
    command: "ifdown {{item.item}}"
    with_items: "{{r_cambiados.results}}"
    when: item.changed

  - name: Subir los interfaces modificados
    command: "ifup {{item.item}}"
    with_items: "{{r_cambiados.results}}"
    when: item.changed

  - name: Crear el directorio /etc/ansible/facts.d
    file:
      path: /etc/ansible/facts.d
      state: directory

  - name: Añadir variables por uso de interface
    set_fact:
      v_network_node: "{{ v_network_node | combine( { v_network_node[item]._use: item },recursive=true ) }}"
    with_items: "{{v_network_node}}"
    when:
      - v_network_node[item]._use in kubeansi.lans or v_network_node[item]._use == 'pxe'

  - name: Guardar los datos de los interfaces en el nodo
    copy:
      dest: /etc/ansible/facts.d/network.fact
      content: "{{v_network_node | to_json}}"
...