---
  v_root:
    dir: /root

  v_tftpboot:
    dir: /var/lib/tftpboot

  v_bootstrap:
    dir: /var/lib/nfs/bootstrap

  v_centos7:
    repo_base: "http://mirror.centos.org/centos/7/os/x86_64"
    nameservers:
      - 8.8.4.4
      - 8.8.8.8
    root_password: "aQZP5m7xBRBt8rtk"
    packages:
      - authconfig
      - bc
      - bridge-utils
      - chrony
      - deltarpm
      - docker-engine-1.12.0
      - epel-release
      - gcc
      - git
      - htop
      - iftop
      - jq
      - mlocate
      - net-tools
      - ntp
      - openvswitch
      - python-devel
      - python2-pip
      - python2-simplejson
      - sg3_utils
      - sudo
      - tcpdump
      - vim-enhanced
#
      - -NetworkManager*
      - -cloud-init
      - -firewalld
      - -iwl*firmware
      - -postfix
      - -python-requests
      - -chrony

    repo_pip:
      - docker
...
