---
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ v_root.dir }}/html"
      - "{{ v_root.dir }}/html/centos7"
      - "{{ v_root.dir }}/html/centos7/LiveOS"
      - "{{ v_root.dir }}/html/centos7/repodata"
      - "{{ v_root.dir }}/html/centos7/Packages"
      - "{{ v_tftpboot.dir }}/centos7"
      - "{{ v_tftpboot.dir }}/uefi"
    tags: pkg

  - name: Bajar los ficheros para el arranque BIOS de CentOS a {{ v_tftpboot.dir }}/centos7
    get_url:
      url: "{{ v_centos7.repo_base }}/images/pxeboot/{{ item }}"
      dest: "{{ v_tftpboot.dir }}/centos7/{{ item }}"
    with_items:
      - vmlinuz
      - initrd.img
    tags: pkg

  - name: Bajar los ficheros para el arranque UEFI de CentOS a {{ v_tftpboot.dir }}/centos7
    get_url:
      url: "{{ v_centos7.repo_base }}/EFI/BOOT/{{ item }}"
      dest: "{{ v_tftpboot.dir }}/{{ item }}"
    with_items:
      - BOOTX64.EFI
      - grubx64.efi
    tags: pkg

  - name: Bajar la imagen de instalación de CentOS a {{ v_root.dir }}/html/centos7
    get_url:
      url: "{{ v_centos7.repo_base }}/LiveOS/squashfs.img"
      dest: "{{ v_root.dir }}/html/centos7/LiveOS/squashfs.img"
    tags: pkg

  - name: Update system packages to repo
    shell: "repoquery -g --grouppkgs=all -l core | xargs repotrack --download_path={{v_root.dir}}/html/centos7/Packages"

  - name: Download repo_packages to repo
    command: "repotrack --download_path={{v_root.dir}}/html/centos7/Packages {{item}}"
    with_items: "{{v_centos7.repo_packages}}"
    when: not item.startswith('-')
    tags: pkg

  - name: Download custom packages to repo
    command: "repotrack --download_path={{v_root.dir}}/html/centos7/Packages {{item}}"
    with_items: "{{v_centos7.packages}}"
    when: not item.startswith('-')
    tags: pkg

  - name: Generate file comps.xml
    template:
      src: comps.xml.j2
      dest: "{{ v_root.dir }}/html/centos7/Packages/comps.xml"
    tags: pkg

  - name: Regenerate repo indexes
    command: "createrepo --groupfile {{ v_root.dir }}/html/centos7/Packages/comps.xml {{ v_root.dir }}/html/centos7"
    tags: pkg
...