---
    - name: Create directories
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - "{{v_root.dir}}/html"

    - name: Install nginx
      yum:
        name: nginx

    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: nginx restart

    - name: Enable nginx service
      service:
        enabled: true
        state: started
        name: nginx
...