---
  - name: SystemD Docker Service Directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      recurse: yes

  - name: Config CGroupDriver
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      force: yes
    notify:
    - docker_status
...