---
  - name: Install base package for docker
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Adds docker repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker-CE
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: SystemD Docker Service Directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      recurse: yes

  - name: Config CGroupDriver
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
    notify:
    - docker_status
...