---
  - name: Kubedeploy
    hosts: nodes
    gather_facts: true
    tasks:
      - name: config
        include_role:
          name: "{{ roles }}"
        with_items:
          - config
          - docker
          - kubernetes
        loop_control:
          loop_var: roles
...