---
  kubeansi:
    name: kubeansi
    domain: example.local
    lan_pxe:
      interface: ens33
      ip: 192.168.5.1
      netmask: 255.255.255.0
      gateway: false
      dhcp_start: 192.168.5.100
      dhcp_end: 192.168.5.200
    lan_control:
      interface: ens37
      ip: 192.168.79.133
      netmask: 255.255.255.0
      gateway: 192.168.79.2
    nameservers:
      - 8.8.4.4
      - 8.8.8.8
...
